export declare const classesBgWhite = "bg-white dark:bg-black";
export declare const classesBgGray = "bg-gray-100 dark:bg-gray-900";
export declare const classesBgAmber = "bg-amber-50 dark:bg-amber-900";
export declare const classesBgYellow = "bg-yellow-50 dark:bg-yellow-900";
export declare const classesBgBlue = "bg-blue-50 dark:bg-blue-950";
export declare const classesBgGreen = "bg-green-100 dark:bg-green-900";
export declare const classesBgGreenLight = "bg-green-50 dark:bg-green-900";
export declare const classesBgRed = "bg-red-100 dark:bg-red-900";
export declare const classesBgSlate = "bg-slate-100 dark:bg-slate-900";
export declare const classesBgPurple = "bg-purple-100 dark:bg-purple-950";
export declare const classesBgStone = "bg-stone-100 dark:bg-stone-900";
//# sourceMappingURL=classesBg.d.ts.map