#!/usr/bin/env bash

# The Caddy file writer is the owner of access.jsonl and its rotated archives.
# project-registryd is root and owns the retention metadata.  This audit is
# intentionally conservative: only the paths and names generated by the
# registry are accepted, and mode repair is allowed only after the entry has
# been proved to be the expected type and owner.

CADDY_ACCESS_LOG_AUDIT_MAX_ENTRIES=4096

caddy_access_log_audit_fail() {
  printf '%s\n' "$1" >&2
  return 1
}

caddy_access_log_audit_count_entry() {
  local path="$1"
  CADDY_ACCESS_LOG_AUDIT_ENTRIES=$((CADDY_ACCESS_LOG_AUDIT_ENTRIES + 1))
  if ((CADDY_ACCESS_LOG_AUDIT_ENTRIES > CADDY_ACCESS_LOG_AUDIT_MAX_ENTRIES)); then
    caddy_access_log_audit_fail "Caddy access-log audit entry limit exceeded: $path"
    return 1
  fi
}

caddy_access_log_audit_owner_ids() {
  local user="$1"
  local group="$2"
  local group_record
  CADDY_ACCESS_LOG_AUDIT_UID="$(id -u -- "$user")" || {
    caddy_access_log_audit_fail "unable to resolve access-log owner user: $user"
    return 1
  }
  group_record="$(getent group -- "$group")" || {
    caddy_access_log_audit_fail "unable to resolve access-log owner group: $group"
    return 1
  }
  group_record="${group_record#*:}"
  group_record="${group_record#*:}"
  CADDY_ACCESS_LOG_AUDIT_GID="${group_record%%:*}"
  [[ "$CADDY_ACCESS_LOG_AUDIT_GID" =~ ^[0-9]+$ ]] || {
    caddy_access_log_audit_fail "unable to resolve access-log owner group: $group"
    return 1
  }
}

caddy_access_log_audit_path_kind() {
  local path="$1"
  if [[ -L "$path" ]]; then
    caddy_access_log_audit_fail "unsafe symbolic link in Caddy access-log storage: $path"
    return 1
  fi
  if [[ -d "$path" || -f "$path" ]]; then return 0; fi
  caddy_access_log_audit_fail "unsafe special file in Caddy access-log storage: $path"
  return 1
}

caddy_access_log_audit_owner() {
  local path="$1"
  local user="$2"
  local group="$3"
  local uid="$4"
  local gid="$5"
  local actual
  actual="$(stat -c '%u:%g' -- "$path")" || {
    caddy_access_log_audit_fail "unable to inspect Caddy access-log ownership: $path"
    return 1
  }
  if [[ "$actual" != "$uid:$gid" ]]; then
    caddy_access_log_audit_fail "Caddy access-log ownership mismatch at $path (expected $user:$group, found $actual)"
    return 1
  fi
}

caddy_access_log_audit_mode() {
  local path="$1"
  local expected_mode="$2"
  local repair="$3"
  local label="$4"
  local actual
  actual="$(stat -c '%a' -- "$path")" || {
    caddy_access_log_audit_fail "unable to inspect Caddy access-log mode: $path"
    return 1
  }
  if [[ "$actual" == "$expected_mode" || "$actual" == "0$expected_mode" ]]; then return 0; fi
  if [[ "$repair" == 1 ]]; then
    chmod "$expected_mode" -- "$path" || {
      caddy_access_log_audit_fail "unable to repair $label mode at $path"
      return 1
    }
    actual="$(stat -c '%a' -- "$path")" || {
      caddy_access_log_audit_fail "unable to verify repaired Caddy access-log mode: $path"
      return 1
    }
    if [[ "$actual" == "$expected_mode" || "$actual" == "0$expected_mode" ]]; then return 0; fi
  fi
  caddy_access_log_audit_fail "Caddy access-log mode is not restrictive at $path (expected $expected_mode, found $actual)"
  return 1
}

caddy_access_log_audit_expected() {
  local path="$1"
  local kind="$2"
  local user="$3"
  local group="$4"
  local uid="$5"
  local gid="$6"
  local mode="$7"
  local repair="$8"
  local label="$9"

  caddy_access_log_audit_count_entry "$path" || return 1
  caddy_access_log_audit_path_kind "$path" || return 1
  if [[ "$kind" == directory ]]; then
    [[ -d "$path" ]] || {
      caddy_access_log_audit_fail "expected Caddy access-log directory is not a directory: $path"
      return 1
    }
  else
    [[ -f "$path" ]] || {
      caddy_access_log_audit_fail "expected Caddy access-log file is not a regular file: $path"
      return 1
    }
  fi
  caddy_access_log_audit_owner "$path" "$user" "$group" "$uid" "$gid" || return 1
  caddy_access_log_audit_mode "$path" "$mode" "$repair" "$label" || return 1
}

caddy_access_log_audit_entries_glob() {
  local directory="$1"
  local entry
  for entry in "$directory"/* "$directory"/.[!.]* "$directory"/..?*; do
    if [[ -e "$entry" || -L "$entry" ]]; then printf '%s\n' "$entry"; fi
  done
}

caddy_access_log_audit_project_directory() {
  local directory="$1"
  local caddy_user="$2"
  local caddy_group="$3"
  local caddy_uid="$4"
  local caddy_gid="$5"
  local daemon_user="$6"
  local daemon_group="$7"
  local daemon_uid="$8"
  local daemon_gid="$9"
  local repair="${10}"
  local entry name

  while IFS= read -r entry; do
    name="${entry##*/}"
    caddy_access_log_audit_path_kind "$entry" || return 1
    case "$name" in
      access.jsonl)
        caddy_access_log_audit_expected "$entry" file "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" 600 "$repair" access-log || return 1
        ;;
      .project-registry-retention.json)
        caddy_access_log_audit_expected "$entry" file "$daemon_user" "$daemon_group" "$daemon_uid" "$daemon_gid" 600 "$repair" metadata || return 1
        ;;
      .project-registry-retention.json.tmp-*)
        [[ "$name" =~ ^\.project-registry-retention\.json\.tmp-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$ ]] || {
          caddy_access_log_audit_fail "unexpected Caddy access-log metadata entry: $entry"
          return 1
        }
        caddy_access_log_audit_expected "$entry" file "$daemon_user" "$daemon_group" "$daemon_uid" "$daemon_gid" 600 "$repair" metadata || return 1
        ;;
      access-*.jsonl|access-*.jsonl.gz)
        [[ "$name" =~ ^access-[A-Za-z0-9_.-]+\.jsonl(\.gz)?$ ]] || {
          caddy_access_log_audit_fail "unexpected Caddy access-log archive entry: $entry"
          return 1
        }
        caddy_access_log_audit_expected "$entry" file "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" 600 "$repair" archive || return 1
        ;;
      *)
        caddy_access_log_audit_fail "unexpected Caddy access-log entry: $entry"
        return 1
        ;;
    esac
  done < <(caddy_access_log_audit_entries_glob "$directory")
}

caddy_access_log_audit_project_namespace() {
  local directory="$1"
  local namespace="$2"
  local caddy_user="$3"
  local caddy_group="$4"
  local caddy_uid="$5"
  local caddy_gid="$6"
  local daemon_user="$7"
  local daemon_group="$8"
  local daemon_uid="$9"
  local daemon_gid="${10}"
  local repair="${11}"
  local entry name

  while IFS= read -r entry; do
    name="${entry##*/}"
    caddy_access_log_audit_path_kind "$entry" || return 1
    [[ "$name" =~ ^[a-f0-9]{64}$ ]] || {
      caddy_access_log_audit_fail "unexpected entry in Caddy access-log $namespace namespace: $entry"
      return 1
    }
    caddy_access_log_audit_expected "$entry" directory "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" 700 "$repair" project-directory || return 1
    caddy_access_log_audit_project_directory "$entry" "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" "$daemon_user" "$daemon_group" "$daemon_uid" "$daemon_gid" "$repair" || return 1
  done < <(caddy_access_log_audit_entries_glob "$directory")
}

# Audit existing storage. Missing root/namespace directories are accepted only
# when the caller is about to create them; the full audit below is required
# after installation. No ownership is repaired.
caddy_access_log_audit_existing() {
  local root="$1"
  local caddy_user="$2"
  local caddy_group="$3"
  local daemon_user="$4"
  local daemon_group="$5"
  local repair="$6"
  local require_namespaces="$7"
  local projects="$root/projects"
  local quarantine="$root/quarantine"
  local entry name

  [[ -n "$root" ]] || return 0
  if [[ ! -e "$root" && ! -L "$root" ]]; then
    [[ "$require_namespaces" == 0 ]] && return 0
    caddy_access_log_audit_fail "Caddy access-log root is missing: $root"
    return 1
  fi

  caddy_access_log_audit_owner_ids "$caddy_user" "$caddy_group" || return 1
  local caddy_uid="$CADDY_ACCESS_LOG_AUDIT_UID"
  local caddy_gid="$CADDY_ACCESS_LOG_AUDIT_GID"
  caddy_access_log_audit_owner_ids "$daemon_user" "$daemon_group" || return 1
  local daemon_uid="$CADDY_ACCESS_LOG_AUDIT_UID"
  local daemon_gid="$CADDY_ACCESS_LOG_AUDIT_GID"
  CADDY_ACCESS_LOG_AUDIT_ENTRIES=0

  caddy_access_log_audit_expected "$root" directory "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" 700 "$repair" root || return 1
  while IFS= read -r entry; do
    name="${entry##*/}"
    caddy_access_log_audit_path_kind "$entry" || return 1
    case "$name" in
      projects)
        caddy_access_log_audit_expected "$entry" directory "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" 700 "$repair" projects || return 1
        caddy_access_log_audit_project_namespace "$entry" projects "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" "$daemon_user" "$daemon_group" "$daemon_uid" "$daemon_gid" "$repair" || return 1
        ;;
      quarantine)
        caddy_access_log_audit_expected "$entry" directory "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" 700 "$repair" quarantine || return 1
        caddy_access_log_audit_project_namespace "$entry" quarantine "$caddy_user" "$caddy_group" "$caddy_uid" "$caddy_gid" "$daemon_user" "$daemon_group" "$daemon_uid" "$daemon_gid" "$repair" || return 1
        ;;
      *)
        caddy_access_log_audit_fail "unexpected entry in Caddy access-log root: $entry"
        return 1
        ;;
    esac
  done < <(caddy_access_log_audit_entries_glob "$root")

  if [[ "$require_namespaces" == 1 ]]; then
    for entry in "$projects" "$quarantine"; do
      [[ -e "$entry" && ! -L "$entry" ]] || {
        caddy_access_log_audit_fail "Caddy access-log namespace is missing: $entry"
        return 1
      }
    done
  fi
}

# Create only absent base directories. Existing entries are audited first and
# are never chowned by this helper; wrong ownership therefore fails closed.
caddy_access_log_root_prepare() {
  local root="$1"
  local caddy_user="$2"
  local caddy_group="$3"
  local install_command="${INSTALL_BIN:-install}"
  local directory

  caddy_access_log_audit_existing "$root" "$caddy_user" "$caddy_group" root root 1 0 || return 1
  for directory in "$root" "$root/projects" "$root/quarantine"; do
    if [[ -e "$directory" || -L "$directory" ]]; then continue; fi
    "$install_command" -d -o "$caddy_user" -g "$caddy_group" -m 0700 -- "$directory" || {
      caddy_access_log_audit_fail "unable to create Caddy access-log directory: $directory"
      return 1
    }
  done
  caddy_access_log_audit_existing "$root" "$caddy_user" "$caddy_group" root root 1 1
}
